# Generated by Django 5.1.4 on 2024-12-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='session',
            field=models.CharField(choices=[('m', 'Morning'), ('a', 'Afternoon'), ('e', 'Evening')], max_length=3),
        ),
    ]
