# Generated by Django 5.1.4 on 2024-12-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_lesson_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='mmh',
            new_name='subject_id',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='mgv',
            new_name='teacher_id',
        ),
    ]
