# Generated by Django 5.1.4 on 2024-12-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_rename_mmh_subject_subject_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AddField(
            model_name='subject',
            name='lesson_count',
            field=models.IntegerField(default=0),
        ),
    ]
