# Generated by Django 5.1.4 on 2024-12-15 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_timetableschedule_timetableassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='timetable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='scheduler.timetableschedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetableschedule',
            name='classes',
            field=models.ManyToManyField(to='scheduler.class'),
        ),
        migrations.AddField(
            model_name='timetableschedule',
            name='teachers',
            field=models.ManyToManyField(to='scheduler.teacher'),
        ),
    ]
