# Generated by Django 5.1.4 on 2024-12-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_timetableschedule_generations_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='lesson_count',
        ),
        migrations.AlterField(
            model_name='subjectschedule',
            name='lesson_count',
            field=models.IntegerField(default=0),
        ),
    ]
