# Generated by Django 5.1.4 on 2024-12-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_remove_subject_lesson_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacherSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='scheduler.class')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='scheduler.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='scheduler.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='scheduler.teacher')),
            ],
            options={
                'verbose_name': 'Class Teacher Schedule',
                'verbose_name_plural': 'Class Teacher Schedules',
                'unique_together': {('semester', 'subject', 'teacher', 'lesson_class')},
            },
        ),
    ]
