# Generated by Django 5.1.4 on 2024-12-26 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_timetableassignment_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablegenerationhistory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
