# Generated by Django 5.1.4 on 2024-12-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_timetablegenerationhistory_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='session',
            field=models.IntegerField(choices=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Evening')]),
        ),
    ]
